function [status result] = SubmitPBSJob(jobstring, jobid, mem)
%Submits job to PBS scheduler on trauma.  Takes as input a string that
%represents the contents of the job file.  This string opens matlab,
%initializes parameter values, calls functions, and exits.  The job string
%is specific to the algorithm and is generated by a separate script given
%parameters values, etc.
%inputs:
%jobstring - Matlab formatted string generated by a function for invoking 
%            matlab code.  Each module should have such a function for
%            automation of job tasks.
%jobid     - Matlab formatted string to assign name to job in PBS
%            scheduler (-N option).
%mem       - (string) free memory parameter 'mem_free', in MB, as defined 
%            by qsub.

fid = fopen('job.sh', 'w'); %create job file in current directory
if(~isspace(jobstring(end)))
    jobstring = sprintf('%s\n', jobstring);
end
fprintf(fid, '%s', jobstring);
fclose(fid);

if(nargin == 1) %submit job without -N
    [status result] = system(['qsub -o /dev/null -e /dev/null -cwd -V -l mem_free=' mem ' -q all.q job.sh']); 
else %submit job with -N option
    if(~isletter(jobid(1))) %fix invalid job ids
        jobid = ['.' jobid];
    end
       
    [status result] = system(['qsub -o /dev/null -e /dev/null -cwd -V -l mem_free=' mem ' -N ' jobid ' -q all.q job.sh']);
end

system('rm job.sh');  %delete job file
