function [Names IsMorph IsIntensity IsTexture IsGradient IsCyto IsHema IsEosin IsGray] = FeatureNames(Augmented)
if(~Augmented)
    Names = {'AREA',...
    'PERIMETER',...
    'ECCENTRICITY',...
    'CIRCULARITY',...
    'MAJOR_AXIS',...
    'MINOR_AXIS',...
    'EXTENT_RATIO',...
    'MEAN_INTENSITY',... %8
    'MAX_INTENSITY',...
    'MIN_INTENSITY',...
    'STD_INTENSITY',...
    'ENTROPY',...   %12
    'ENERGY',...
    'SKEWNESS',...
    'KURTOSIS',...
    'MEAN_GRADIENT_MAGNITUDE',...   %16
    'STD_GRADIENT_MAGNITUDE',...
    'ENTROPY_GRADIENT_MAGNITUDE',...
    'ENERGY_GRADIENT_MAGNITUDE',...
    'SKEWNESS_GRADIENT_MAGNITUDE',...
    'KURTOSIS_GRADIENT_MAGNITUDE',...
    'SUM_CANNY_PIXEL',...
    'MEAN_CANNY_PIXEL'}.';

    IsMorph = false(size(Names)); IsMorph(1:7) = true;
    IsIntensity = false(size(Names)); IsIntensity(7:11) = true;
    IsTexture = false(size(Names)); IsTexture(12:15) = true;
    IsGradient = false(size(Names)); IsGradient(16:end) = true;
    IsCyto = false(size(Names));
    IsHema = false(size(Names));
    IsEosin = false(size(Names));
    IsGray = false(size(Names));

else
    Names = {'AREA',...
    'PERIMETER',...
    'ECCENTRICITY',...
    'CIRCULARITY',...
    'MAJOR_AXIS',...
    'MINOR_AXIS',...
    'EXTENT_RATIO',...
    'MEAN_INTENSITY',... %8
    'MAX_INTENSITY',...
    'MIN_INTENSITY',...
    'STD_INTENSITY',...
    'ENTROPY',...   %12
    'ENERGY',...
    'SKEWNESS',...
    'KURTOSIS',...
    'MEAN_GRADIENT_MAGNITUDE',...   %16
    'STD_GRADIENT_MAGNITUDE',...
    'ENTROPY_GRADIENT_MAGNITUDE',...
    'ENERGY_GRADIENT_MAGNITUDE',...
    'SKEWNESS_GRADIENT_MAGNITUDE',...
    'KURTOSIS_GRADIENT_MAGNITUDE',...
    'SUM_CANNY_PIXEL',...
    'MEAN_CANNY_PIXEL',...
    'CYTO_H_MeanIntensity',...  %24
    'CYTO_H_MeanMedianDifferenceIntensity',...
    'CYTO_H_MaxIntensity',...
    'CYTO_H_MinIntensity',...
    'CYTO_H_StdIntensity',...
    'CYTO_H_Entropy',...    %29
    'CYTO_H_Energy',...
    'CYTO_H_Skewness',...
    'CYTO_H_Kurtosis',...
    'CYTO_H_MeanGradMag',...    %33
    'CYTO_H_StdGradMag',...
    'CYTO_H_EntropyGradMag',...
    'CYTO_H_EnergyGradMag',...
    'CYTO_H_SkewnessGradMag',...
    'CYTO_H_KurtosisGradMag',...
    'CYTO_H_SumCanny',...
    'CYTO_H_MeanCanny',...
    'CYTO_E_MeanIntensity',... %41
    'CYTO_E_MeanMedianDifferenceIntensity',...
    'CYTO_E_MaxIntensity',...
    'CYTO_E_MinIntensity',...
    'CYTO_E_StdIntensity',...
    'CYTO_E_Entropy',...    %46
    'CYTO_E_Energy',...
    'CYTO_E_Skewness',...
    'CYTO_E_Kurtosis',...
    'CYTO_E_MeanGradMag',...    %50
    'CYTO_E_StdGradMag',...
    'CYTO_E_EntropyGradMag',...
    'CYTO_E_EnergyGradMag',...
    'CYTO_E_SkewnessGradMag',...
    'CYTO_E_KurtosisGradMag',...
    'CYTO_E_SumCanny',...
    'CYTO_E_MeanCanny',...
    'CYTO_G_MeanIntensity',...  %58
    'CYTO_G_MeanMedianDifferenceIntensity',...
    'CYTO_G_MaxIntensity',...
    'CYTO_G_MinIntensity',...
    'CYTO_G_StdIntensity',...
    'CYTO_G_Entropy',...    %63
    'CYTO_G_Energy',...
    'CYTO_G_Skewness',...
    'CYTO_G_Kurtosis',...
    'CYTO_G_MeanGradMag',...    %67
    'CYTO_G_StdGradMag',...
    'CYTO_G_EntropyGradMag',...
    'CYTO_G_EnergyGradMag',...
    'CYTO_G_SkewnessGradMag',...
    'CYTO_G_KurtosisGradMag',...
    'CYTO_G_SumCanny',...
    'CYTO_G_MeanCanny'}.';

    %nuclear features
    IsMorph = false(size(Names)); IsMorph(1:7) = true;
    IsIntensity = false(size(Names)); IsIntensity(8:11) = true;
    IsTexture = false(size(Names)); IsTexture(12:15) = true;
    IsGradient = false(size(Names)); IsGradient(16:23) = true;
    
    %cytoplasm features
    IsCyto = false(size(Names)); IsCyto(24:end) = true;
    
    %hematoxylin features
    IsHema = false(size(Names)); IsHema(24:40) = true;
    IsIntensity(24:28) = true;
    IsTexture(29:32) = true;
    IsGradient(33:40) = true;    
    
    %eosin features
    IsEosin = false(size(Names)); IsEosin(41:57) = true;
    IsIntensity(41:45) = true;
    IsTexture(46:49) = true;
    IsGradient(50:57) = true;
    
    %grayscale features
    IsGray = false(size(Names)); IsGray(58:end) = true;
    IsIntensity(58:62) = true;
    IsTexture(63:66) = true;
    IsGradient(67:74) = true;

end