close all;
clear all;

       
dirs = {...
    '/home/tcpan/PhD/path/Data/adios/kfs-syntest-param2', ... 
    '/home/tcpan/PhD/path/Data/adios/kfs-syntest-param1', ... 
    '/home/tcpan/PhD/path/Data/adios/keeneland-syntest-params3', ...    
    '/home/tcpan/PhD/path/Data/adios/keeneland-syntest-params2', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-nb-vs-b3', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-nb-vs-b2', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-nb-vs-b', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-compress-cap3', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-compress-cap2', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-compress-cap1', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-compressed1', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-5', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-4', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-3', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-2', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-hpdc2012-1', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput',...
    '/home/tcpan/PhD/path/Data/adios/jaguar-hpdc2012-weak1', ...
    '/home/tcpan/PhD/path/Data/adios/jaguar-tcga-transports-sep_osts', ...
    '/home/tcpan/PhD/path/Data/adios/jaguar-tcga-transports', ...
    '/home/tcpan/PhD/path/Data/adios/jaguar-tcga-strong2', ...
    '/home/tcpan/PhD/path/Data/adios/jaguar-tcga-strong1', ...
    '/home/tcpan/PhD/path/Data/adios/jaguar-tcga-async1' ...
};


%selections = [3 4 5];
selections = 1:length(dirs);

    
for j = 1 : length(selections)
        id = selections(j);
        dirname = dirs{id};
    
        

        % for testing
        files = dir(fullfile(dirname, '*.csv'));
        
        for i = 1:length(files)
            [~, n, ~] = fileparts(files(i).name);
            prefix = fullfile(dirname, n);
            fprintf(1, 'filename is %s\n', prefix);
            
            if (exist([prefix '.stat_by_events.mat']) == 2)
                load([prefix '.stat_by_events.mat']);
                
                save([prefix '.events_pid.mat'], 'events_pid', 'fields', 'nodeTypes');
                save([prefix '.events_stats.mat'], 'summary_pid', 'ops_pid', 'allEventTypes');
                clear summary_pid ops_pid allEventTypes allTypeNames events_pid fields nodeTypes TPIntervals interval;
            else
                fprintf(1, 'NO MATCHING %s\n', prefix);
            end

        end
    end

% end










