#!/bin/sh
source /nics/c/home/tcpan/env.sh
DATA_DIR="/nics/c/home/tcpan/data/ValidationSet/20X_4096x4096_tiles/astroII.1"
EXE_DIR="/nics/c/home/tcpan/projects/nscale/src/segment"
find ${DATA_DIR} -name "*.tif" -print0 | xargs -0 -I fn ${EXE_DIR}/nu-segment.exe fn gpu 0
find ${DATA_DIR} -name "*.tif" -print0 | xargs -0 -I fn ${EXE_DIR}/nu-segment.exe fn cpu

