close all;
clear all;


allEventTypes = [-1 0 11 12 21 22 31 32 41 42 43 44 45 46]';
colorMap = [0, 0, 0; ...                    % OTHER, -1, black
            120.0, 0.4, 1.0; ...      % COMPUTE, 0, green
            240.0, 0.4, 1.0; ...      % MEM_IO, 11, blue
            240.0, 0.4, 1.0; ...      % GPU_MEM_IO, 12, blue
            180.0, 0.4, 1.0; ...      % NETWORK_IO, 21, cyan
            300.0, 0.4, 1.0; ...      % NETWORK_WAIT, 22, magenta
            60.0, 0.4, 1.0; ...       % FILE_I, 31, yellow
            0.0, 0.4, 1.0; ...        % FILE_O, 32, red
            180.0, 1.0, 1.0; ...      % ADIOS_INIT, 41, cyan
            300.0, 1.0, 1.0; ...      % ADIOS_OPEN, 42, magenta
            240.0, 1.0, 1.0; ...      % ADIOS_ALLOC, 43, blue
            60.0, 1.0, 1.0; ...       % ADIOS_WRITE, 44, yellow
            0.0, 1.0, 1.0; ...        % ADIOS_CLOSE, 45, red
            120.0, 1.0, 1.0; ...      % ADIOS_FINALIZE, 46, green
];
colorMap(:, 1) = colorMap(:, 1) / 180.0 * pi;  % in radian
allTypeNames = {'Other',...
    'Compute',...
    'Mem IO',...
    'GPU mem IO', ...
    'Network IO', ...
    'Network wait', ...
    'File read', ...
    'File write', ...
    'ADIOS init', ...
    'ADIOS open', ...
    'ADIOS alloc', ...
    'ADIOS write', ...
    'ADIOS close', ...
    'ADIOS finalize'};
        

close all;
fid = fopen('/home/tcpan/PhD/path/Data/adios/yellowstone_throughput.csv', 'w');
prefixes = { ...
    '/home/tcpan/PhD/path/Data/adios/yellowstone/posix-seg-tests', ...
    '/home/tcpan/PhD/path/Data/adios/yellowstone/adios-seg-tests-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/yellowstone/adios-seg-tests-MPI' ...
};
%    '/home/tcpan/PhD/path/Data/adios/yellowstone/adios-seg-tests-NULL',

timeInterval = 1000; % 100 millisec
procWidth = 300;

for i = 1:length(prefixes)
    prefix = prefixes{i};
    proc_events = readComputeAndIOTimingOneLineFormat([prefix '.csv']);
    plotProcEvents(proc_events, procWidth, timeInterval, prefix, allEventTypes, colorMap);
    fprintf(fid, '%s\n', prefix);
    summarize(proc_events, timeInterval, fid, 'w', allEventTypes, allTypeNames);
end

fclose(fid);


close all;
fid = fopen('/home/tcpan/PhD/path/Data/adios/tcga_small_throughput.csv', 'w');
prefixes = { ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small1/posix-tcga_small', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small1/adios-tcga_small-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small1/adios-tcga_small-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small1/adios-tcga_small-MPI', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small1/adios-tcga_small-MPI_LUSTRE', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small1/adios-tcga_small-MPI_AMR', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small2/posix-tcga_small', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small2/adios-tcga_small-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small2/adios-tcga_small-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small2/adios-tcga_small-MPI', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small2/adios-tcga_small-MPI_LUSTRE', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small2/adios-tcga_small-MPI_AMR', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small3-throughput/posix-tcga_small', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small3-throughput/adios-tcga_small-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small3-throughput/adios-tcga_small-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small3-throughput/adios-tcga_small-MPI', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small3-throughput/adios-tcga_small-MPI_LUSTRE', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga-small3-throughput/adios-tcga_small-MPI_AMR' ...
};

timeInterval = 20000; % 20 millisec
procWidth = 20;

for i = 1:length(prefixes)
    prefix = prefixes{i};
    proc_events = readComputeAndIOTimingOneLineFormat([prefix '.csv']);
    [img norm_events] = plotProcEvents(proc_events, procWidth, timeInterval, prefix, allEventTypes, colorMap);
    fprintf(fid, '%s\n', prefix);
    summarize(proc_events, timeInterval, fid, 'w', allEventTypes, allTypeNames);
end

fclose(fid);



close all;
fid = fopen('/home/tcpan/PhD/path/Data/adios/tcga_throughput.csv', 'w');
prefixes = { ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga1/posix-tcga', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga1/adios-tcga-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga1/adios-tcga-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga2/posix-tcga', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga2/adios-tcga-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga2/adios-tcga-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga2/adios-tcga-MPI', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga2/adios-tcga-MPI_LUSTRE', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga2/adios-tcga-MPI_AMR', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput/posix-tcga', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput/adios-tcga-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput/adios-tcga-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput/adios-tcga-MPI', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput/adios-tcga-MPI_LUSTRE', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga3-throughput/adios-tcga-MPI_AMR', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga4-throughput-smallAMR/posix-tcga', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga4-throughput-smallAMR/adios-tcga-NULL', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga4-throughput-smallAMR/adios-tcga-POSIX', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga4-throughput-smallAMR/adios-tcga-MPI', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga4-throughput-smallAMR/adios-tcga-MPI_LUSTRE', ...
    '/home/tcpan/PhD/path/Data/adios/keeneland-tcga4-throughput-smallAMR/adios-tcga-MPI_AMR' ...
};

timeInterval = 100000; % 100 millisec
procWidth = 20;

for i = 1:length(prefixes)
    prefix = prefixes{i};
    proc_events = readComputeAndIOTimingOneLineFormat([prefix '.csv']);
    [img norm_events] = plotProcEvents(proc_events, procWidth, timeInterval, prefix, allEventTypes, colorMap);
    fprintf(fid, '%s\n', prefix);
    summarize(proc_events, timeInterval, fid, 'w', allEventTypes, allTypeNames);
end

fclose(fid);








